
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages: 
        javascript:
ratings:
  paths:
    - "server/"

exclude_paths:
  - "test/"
  - "seeders/"
  - "migrations/"
  - "config/"